apiVersion: v1
kind: PersistentVolume
metadata:
  name: app01-db     # penamaan pv
  labels:
    app: app01-db   # penamaan label pv
    tier: mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: master
    # Exported path of your NFS server
    path: "/var/lib/nfs-share/app01/db"