apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app01-db            # penamaan pvc
  labels:
    app: app01-db           # penamaan label pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi