apiVersion: v1
kind: Service
metadata:
  name: httpd-tes00-service
spec:
  selector:
    app: httpd
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30070
    protocol: TCP