apiVersion: v1
kind: PersistentVolume
metadata:
  name: app01-web          # penamaan pv
  labels:
    app: app01-web         # penamaan label pv
    tier: frontend
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: master
    # Exported path of your NFS server
    path: "/var/lib/nfs-share/app01/web"
    